### ISSUE TITLE
"*" resources is not a too wide permission?

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cloudformation#7]
Here: https://github.com/kubecost/cloudformation/blob/4d5c48ea7009a208a67c727203f8052c342f052d/kubecost-sub-account-permissions.yaml#L71

**Comment by pierluigilenoci** [comment]
@AjayTripathy any feedback?

**Comment by AjayTripathy** [comment]
This sounds reasonable, but our plan is to eventually deprecate the spot feed in favor of only pulling reconciled pricing data from athena.

**Comment by pierluigilenoci** [comment]
@dwbrown2 four months has passed, is there any news?

**Comment by pierluigilenoci** [comment]
@AjayTripathy 

![200](https://user-images.githubusercontent.com/36044817/130442235-9438a8ae-8054-45cc-9c8a-2f866827ebd5.gif)

**Comment by AjayTripathy** [comment]
Thanks for checking back in, I've tagged this as help wanted.

**Comment by pierluigilenoci** [comment]
@AjayTripathy any news?

**Comment by AjayTripathy** [comment]
Thank you for your patience, we will continue to make improvements on the CFN templates but no updates yet. You're always welcome to use more restrictive permissions where it makes sense in your own IAM rules.

**Comment by pierluigilenoci** [comment]
![hopes-and-dreams-barney-hopes](https://github.com/kubecost/cloudformation/assets/36044817/600d6ab5-2a75-4c40-91fb-9a021707d19f)
