### ISSUE TITLE
"*" resources is not a too wide permission?

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cloudformation#8]
Here: 
https://github.com/kubecost/cloudformation/blob/4d5c48ea7009a208a67c727203f8052c342f052d/kubecost-masterpayer-account-permissions.yaml#L39

**Comment by pierluigilenoci** [comment]
@AjayTripathy any feedback?

**Comment by AjayTripathy** [comment]
This sounds reasonable, apprecate the patience as we're a little backed up here. For context it should be possible to get fine grained access but would need to investigate. Dropping some notes here in case someone else can pick up. https://docs.aws.amazon.com/athena/latest/ug/fine-grained-access-to-glue-resources.html

**Comment by pierluigilenoci** [comment]
@dwbrown2 four months have passed, is there any news?

**Comment by pierluigilenoci** [comment]
@AjayTripathy 

![200](https://user-images.githubusercontent.com/36044817/130442281-d3f6ae3f-2afc-4ef6-9993-87c497f651bd.gif)

**Comment by AjayTripathy** [comment]
Thanks for checking back in, I've tagged this as help wanted.

**Comment by srpomeroy** [comment]
We've added support for workgroups other than `primary` and have an updated IAM policy to match. I will open a PR soon to update the CFT.

**Comment by pierluigilenoci** [comment]
@srpomeroy any news?

**Comment by pierluigilenoci** [comment]
![hopes-and-dreams-barney-hopes](https://github.com/kubecost/cloudformation/assets/36044817/97c0ebab-0654-4bbe-bf31-468511f6a40b)
