### ISSUE TITLE
Too wide permissions for sub-accounts 

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cloudformation#9]
This can be a security issue because all roles of the child account can access the CUR data in this way. https://github.com/kubecost/cloudformation/blob/4d5c48ea7009a208a67c727203f8052c342f052d/kubecost-masterpayer-account-permissions.yaml#L24

The safest solution is to restrict only to the role created here: https://github.com/kubecost/cloudformation/blob/master/kubecost-sub-account-permissions.yaml#L18

**Comment by pierluigilenoci** [comment]
@AjayTripathy any feedback?

**Comment by AjayTripathy** [comment]
That sounds reasonable-- we'll look to add this to our CFN template. We're just a little backed up so appreciate your patience.

**Comment by pierluigilenoci** [comment]
In this way all IAM user inside the Kubecost Cluster AWS Account are able to read Athena dbs.
Ref: https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-cli/

**Comment by pierluigilenoci** [comment]
@AjayTripathy any news about this?

**Comment by pierluigilenoci** [comment]
@dwbrown2 four months have passed, is there any news?

**Comment by pierluigilenoci** [comment]
@AjayTripathy 

![Uploading 200.gif…]()

**Comment by pierluigilenoci** [comment]
@AjayTripathy 

![200](https://user-images.githubusercontent.com/36044817/130442384-55fba91f-db8d-468e-9d09-5b93d5fe1fe7.gif)

**Comment by pierluigilenoci** [comment]
@AjayTripathy any update?

**Comment by AjayTripathy** [comment]
Thank you for your patience, we will continue to make improvements on the CFN templates but no updates yet. You're always welcome to use more restrictive permissions where it makes sense in your own IAM rules.

**Comment by pierluigilenoci** [comment]
![hopes-and-dreams-barney-hopes](https://github.com/kubecost/cloudformation/assets/36044817/98439375-3f34-43c0-8409-cae006ce5aa0)
